### ISSUE TITLE
Support external libs instead of fetching duplicates

### ISSUE THREAD

**Issue by barracuda156** [NikolaDucak/caps-log#55]
Could you provide an option to use pre-installed `FTXUI` and `libfmt` instead of forcing a fetch? That would be helpful for MacPorts.

**Comment by NikolaDucak** [comment]
Hi, sure thanks for the suggestion!

**Comment by barracuda156** [comment]
@NikolaDucak By the way, this breaks finding Boost: `set(Boost_USE_STATIC_LIBS ON)`. Not sure why; but commenting it out works.

**Comment by barracuda156** [comment]
P. S. This is actually needed, since if you build with FTXUI installed, but without patching CMakeLists, this happens:
```
36-178% /opt/local/bin/caps-log
dyld: Library not loaded: /opt/local/lib/libftxui-component.5.0.0.dylib
  Referenced from: /opt/local/bin/caps-log
  Reason: image not found
zsh: trace trap  /opt/local/bin/caps-log
```

**Comment by barracuda156** [comment]
Boost issue is relevant; dyld issue is solved by your latest commit (I just trying to build with bundled libs first).

**Comment by NikolaDucak** [comment]
Regarding the boost issue, I think removing the explicitly set boost version should fix the Portfile error

**Comment by NikolaDucak** [comment]
> Regarding the boost issue, I think removing the explicitly set boost version should fix the Portfile error

that wasn't the fix, ive removed the static libs flag from the CMake file and now it's used only for the release pipeline that builds the binary artefacts
